version: 2.1

orbs:
  architect: giantswarm/architect@9.5.3

workflows:
  test:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: nancy-fixer
        resource_class: large
        architectures: "linux/amd64,linux/arm64,darwin/amd64,darwin/arm64,windows/amd64,windows/arm64"
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        platforms: "linux/amd64,linux/arm64"
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master

    - architect/upload-release-assets:
        binary: nancy-fixer
        context: architect
        name: upload-release-assets
        requires:
        - go-build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
